name: BookwormPlugin
version: 1.0.0
main: de.fabianholzwarth.BookwormPlugin
description: Show players a preview of the targeted book inside a chiseled bookshelf
author: Fabian Holzwarth
website: https://fabianholzwart.de
api-version: '1.20'