name: BookwormPlugin
version: 0.0.1
main: de.fabianholzwarth.BookwormPlugin
description: Show players a preview of the targeted book inside a chiseled bookshelf
author: Fabian Holzwarth
website: https://fabianholzwart.de
api-version: '1.20'